import { Inter } from 'next/font/google'

import './globals.css'

import SessionWrapper from '@/components/layout/session-provider/session-wrapper'
import Auth from '@/components/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params: { session, ...params} }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper session={session}>
          <Auth />
          {children}
        </SessionWrapper>
      </body>
    </html>
  )
}
