import { cookies } from 'next/headers'
import { Inter } from 'next/font/google'

import Navbar from '@/components/layout/navbar'
import LayoutWrapper from '@/components/layout/wrapper'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  const token = cookies().get('token')
  
  return (
    <html lang="pl">
      <body className={inter.className}>
        <LayoutWrapper isLogged={Boolean(token?.value)}>
          <Navbar />
          {children}      
        </LayoutWrapper>
      </body>
    </html>
  )
}
